# Generated by Django 3.2.5 on 2021-07-20 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Movie', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='movietoactor', to='movies.actor')),
                ('actor', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='actortomovie', to='movies.actor')),
            ],
            options={
                'db_table': 'actormovies',
            },
        ),
    ]
