# Generated by Django 3.2.5 on 2021-07-20 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_actormovie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actormovie',
            name='Movie',
        ),
        migrations.AddField(
            model_name='actormovie',
            name='movie',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
        ),
        migrations.AlterField(
            model_name='actormovie',
            name='actor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='movies.actor'),
        ),
    ]
